### PR TITLE
fix(python): python synthesizer improperly handling f strings in resource props

### LINKED ISSUE #455: Multiline strings aren't correctly formatted in python
The template 
```
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StaticExternalIp
      Description: Lambda Function with code to call an external service
      Code:
        ZipFile: !Sub |
          const https = require('https');

          exports.handler = async (event) => {
            const url = 'https://api.ipify.org';
            let data = "";

            return new Promise((resolve) => {
              https.get(url, res => {

              res.on('data', chunk => { data += chunk }) 

              res.on('end', () => {
                resolve(data);
                })
              }) 
            })
          };
``` 
is formatted into a string that does not synth.

### PR DESCRIPTION
**Pull request by HBobertz**
- minor comment update
- fix multiline bug with sub parts

Fixes #455 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by TheRealAmazonKendra** [comment]
How did you test that this synths and deploys?

**Comment by TheRealAmazonKendra** [comment]
This case fails for this solution 
```
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: StaticExternalIp
      Description: Lambda Function with code to call an external service
      Code:
        ZipFile: !Sub |
          const https = require('https');

          exports.handler = async (event) => {
            const url = 'https://api.ipify.org';
            let data = "";

            return new Promise((resolve) => {
              https.get(url, res => {

              res.on('data', chunk => { data += chunk }) 

              res.on('end', () => {
                resolve(data);
                })
              }) 
            })
          };
```

**Comment by HBobertz** [comment]
> This case fails for this solution
> 
> ```
>   LambdaFunction:
>     Type: AWS::Lambda::Function
>     Properties:
>       FunctionName: StaticExternalIp
>       Description: Lambda Function with code to call an external service
>       Code:
>         ZipFile: !Sub |
>           const https = require('https');
> 
>           exports.handler = async (event) => {
>             const url = 'https://api.ipify.org';
>             let data = "";
> 
>             return new Promise((resolve) => {
>               https.get(url, res => {
> 
>               res.on('data', chunk => { data += chunk }) 
> 
>               res.on('end', () => {
>                 resolve(data);
>                 })
>               }) 
>             })
>           };
> ```

I haven't tested deploying it but this successfully synthesizes for me. What error were you getting

**Comment by TheRealAmazonKendra** [comment]
Apologies. I hadn't updated a typo that this test case had in it so the failure was completely unrelated. I reran it and it's all good.

**Review by TheRealAmazonKendra — APPROVED** [review]

**Pull request merged**
