### PR TITLE
fix(csharp): StackProps are renamed when no stack props are present

### PR DESCRIPTION
**Pull request by TheRealAmazonKendra**
We should only be renaming `StackProps` when there are props present. If none are, we just won't add the structure or rename the stack props.

This is also how Java is structured.

This is part 1 of the fix but it will unblock the tests in the CLI.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by HBobertz** [comment]
Should have provided more context on my pr https://github.com/cdklabs/cdk-from-cfn/pull/279/files. Can you explain how you plan to handle the stack props in the CDK CLI?

**Review by HBobertz — CHANGES_REQUESTED** [review]
Pulled down the PR. Creates the previous error still: 
```
/Users/bobertzh/work/deleteme/temp/myTemp/src/MyTemp/Program.cs(13,44): error CS1503: Argument 3: cannot convert from 'Amazon.CDK.StackProps' to 'MyTempStack.MyTempStackProps' [/Users/bobertzh/work/deleteme/temp/myTemp/src/MyTemp/MyTemp.csproj]
```

If we are going to implement java's prop overrides instead of using an empty props class can we do that here?

**Comment by TheRealAmazonKendra** [comment]
> Pulled down the PR. Creates the previous error:
> 
> ```
> /Users/bobertzh/work/deleteme/temp/myTemp/src/MyTemp/Program.cs(13,44): error CS1503: Argument 3: cannot convert from 'Amazon.CDK.StackProps' to 'MyTempStack.MyTempStackProps' [/Users/bobertzh/work/deleteme/temp/myTemp/src/MyTemp/MyTemp.csproj]
> ```
> 
> If we are going to implement java's prop overrides instead of using an empty props class can we do that here as well?

Yes, I did the half here that would fix the use case we're testing against in the CLI integ tests to unblock upgrading on that end and then was working on doing the other half as a fast follow up.

**Comment by HBobertz** [comment]
I am going to take a harder line and say this is also not consistent with CSharp documentation https://docs.aws.amazon.com/cdk/v2/guide/stack_how_to_create_multiple_stacks.html#cdk-how-to-create-multiple-stacks-extend-stackprops

**Pull request closed without merging**
