### PR TITLE
fix(python): python reserved keywords overlapping with service names

### PR DESCRIPTION
**Pull request by HBobertz**
Previously python apps would fail lambda because we would be using the keyword lambda. i.e.
```
import aws_cdk.aws_lambda as lambda

lambdaFunction = lambda.CfnFunction(self, 'LambdaFunction'
```

fixed by only adding `aws_` before a lambda import
```
import aws_cdk.aws_lambda as aws_lambda

lambdaFunction = aws_lambda.CfnFunction(self, 'LambdaFunction'
```

Fixes # https://github.com/cdklabs/cdk-from-cfn/issues/319

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Review by TheRealAmazonKendra — CHANGES_REQUESTED** [review]
I think we should use the `aws_` convention across the board for consistency. There may be other services we haven't discovered yet that are also reserved keywords.

**Comment by TheRealAmazonKendra** [comment]
Also, please link the issue you're fixing in the PR body.

**Comment by HBobertz** [comment]
> I think we should use the `aws_` convention across the board for consistency. There may be other services we haven't discovered yet that are also reserved keywords.

https://docs.aws.amazon.com/cdk/v2/guide/hello_world.html#hello_world_tutorial_add_bucket

I think this is more aligned with how we do this in python. So I'd personally like to keep it

**Comment by TheRealAmazonKendra** [comment]
Do we know for sure that other service names aren't reserved keywords? Making the change on the whole safeguards us from that being an issue for other services. When that example was written, that issue probably wasn't in the forefront of their mind

**Comment by HBobertz** [comment]
> Do we know for sure that other service names aren't reserved keywords? Making the change on the whole safeguards us from that being an issue for other services. When that example was written, that issue probably wasn't in the forefront of their mind.

https://docs.python.org/2.5/ref/keywords.html 
https://docs.aws.amazon.com/

Compared the list of Python keywords and the AWS services. There doesn't seem to be any other keyword overlap between the two.

**Review by madeline-k — APPROVED** [review]

**Pull request merged**
